#!/bin/bash

set -e

micropcf_dir=$(cd `dirname $0` && cd ../.. && pwd)
images_dir=$micropcf_dir/images
output_dir=$images_dir/micropcf/output
mkdir -p "$output_dir"

"$micropcf_dir/bosh/setup-packer" "$output_dir/packer-bosh"

releases='cf-rabbitmq diego cf garden-linux etcd cf-redis cf-mysql'
if ! "$micropcf_dir/bosh/retrieve" "$output_dir/assets" $releases; then
  "$micropcf_dir/bosh/build" "$output_dir/assets" $releases
fi

cp -a "$images_dir"/{http,scripts} "$output_dir/"
cp -a "$images_dir/micropcf/post-run" "$output_dir/scripts/"
spiff merge "$images_dir/micropcf/manifest.yml" "$images_dir/manifest.yml" > "$output_dir/manifest.yml"

pushd "$output_dir" >/dev/null
  packer build $@ -var 'distro=micropcf' "$images_dir/micropcf.json"
popd >/dev/null
