#!/bin/bash

set -e

if [[ -z $1 ]] || [[ ! -d $(dirname "$1") ]]; then
  >&2 echo "Usage:"
  >&2 echo -e "\t$0 /path/to/assets [first-release] [second-release] ..."
  exit 1
fi


assets_dir=$(mkdir -p "$1" && cd "$1" && pwd)
pcfdev_dir=$(cd `dirname $0` && cd .. && pwd)
releases=${@:2}

if "$pcfdev_dir/bin/assets-present" $releases && ! "$pcfdev_dir/bin/assets-clean" $releases; then
  >&2 echo "Assets are available but dirty."
  exit 1
fi

signature=$("$pcfdev_dir/bin/asset-signature" $releases)
if [[ -z $signature ]]; then
  >&2 echo "Assets not available in cache."
  exit 1
fi

aws s3api get-object --bucket pcfdev --key "asset-cache/${signature}.tar" >(tar -C "$assets_dir" -x)
