#!/bin/bash

set -eu

domain=$1

cf_api_url="api.$domain"
cf_admin_username='admin'
cf_admin_password='admin'

broker_username='admin'
broker_password='admin'

function updateServiceBroker() {
  echo "Service broker already exists - updating broker"
  cf update-service-broker ${broker_name} ${broker_username} ${broker_password} ${broker_url}
}

function createServiceBroker(){
  echo "Service broker does not exist - creating broker"
  cf create-service-broker ${broker_name} ${broker_username} ${broker_password} ${broker_url}
}

cf api ${cf_api_url} --skip-ssl-validation
cf auth ${cf_admin_username} ${cf_admin_password}

broker_name='p-mysql'
broker_url="http://mysql-broker.$domain"

createServiceBroker || updateServiceBroker
cf enable-service-access ${broker_name}

broker_name='p-redis'
broker_url="http://redis-broker.$domain"

createServiceBroker || updateServiceBroker
cf enable-service-access ${broker_name}

broker_name='p-rabbitmq'
broker_url="http://rabbitmq-broker.$domain"

createServiceBroker || updateServiceBroker
cf enable-service-access ${broker_name}
